package thess.tourism.creative.creativetourismthessapp.DbFiles;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CATEGORY.
 */
public class Category {

    private Long id;
    private String NameEn;
    private String NameEl;

    public Category() {
    }

    public Category(Long id) {
        this.id = id;
    }

    public Category(Long id, String NameEn, String NameEl) {
        this.id = id;
        this.NameEn = NameEn;
        this.NameEl = NameEl;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNameEn() {
        return NameEn;
    }

    public void setNameEn(String NameEn) {
        this.NameEn = NameEn;
    }

    public String getNameEl() {
        return NameEl;
    }

    public void setNameEl(String NameEl) {
        this.NameEl = NameEl;
    }

}
