package thess.tourism.creative.creativetourismthessapp.DbFiles;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CREATOR.
 */
public class Creator {

    private Long id;
    private String NameEn;
    private String NameEl;
    private String Organization;
    private String JobEn;
    private String JobEl;
    private String AddressEn;
    private String AddressEl;
    private String websiteAddress;
    private Double lat;
    private Double longitude;
    private Long categoryId;
    private Long startingPointId;
    private String map_image;
    private String details_image;

    public Creator() {
    }

    public Creator(Long id) {
        this.id = id;
    }

    public Creator(Long id, String NameEn, String NameEl, String Organization, String JobEn, String JobEl, String AddressEn, String AddressEl, String websiteAddress, Double lat, Double longitude, Long categoryId, Long startingPointId, String map_image, String details_image) {
        this.id = id;
        this.NameEn = NameEn;
        this.NameEl = NameEl;
        this.Organization = Organization;
        this.JobEn = JobEn;
        this.JobEl = JobEl;
        this.AddressEn = AddressEn;
        this.AddressEl = AddressEl;
        this.websiteAddress = websiteAddress;
        this.lat = lat;
        this.longitude = longitude;
        this.categoryId = categoryId;
        this.startingPointId = startingPointId;
        this.map_image = map_image;
        this.details_image = details_image;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNameEn() {
        return NameEn;
    }

    public void setNameEn(String NameEn) {
        this.NameEn = NameEn;
    }

    public String getNameEl() {
        return NameEl;
    }

    public void setNameEl(String NameEl) {
        this.NameEl = NameEl;
    }

    public String getOrganization() {
        return Organization;
    }

    public void setOrganization(String Organization) {
        this.Organization = Organization;
    }

    public String getJobEn() {
        return JobEn;
    }

    public void setJobEn(String JobEn) {
        this.JobEn = JobEn;
    }

    public String getJobEl() {
        return JobEl;
    }

    public void setJobEl(String JobEl) {
        this.JobEl = JobEl;
    }

    public String getAddressEn() {
        return AddressEn;
    }

    public void setAddressEn(String AddressEn) {
        this.AddressEn = AddressEn;
    }

    public String getAddressEl() {
        return AddressEl;
    }

    public void setAddressEl(String AddressEl) {
        this.AddressEl = AddressEl;
    }

    public String getWebsiteAddress() {
        return websiteAddress;
    }

    public void setWebsiteAddress(String websiteAddress) {
        this.websiteAddress = websiteAddress;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public Long getCategoryId() {
        return categoryId;
    }

    public void setCategoryId(Long categoryId) {
        this.categoryId = categoryId;
    }

    public Long getStartingPointId() {
        return startingPointId;
    }

    public void setStartingPointId(Long startingPointId) {
        this.startingPointId = startingPointId;
    }

    public String getMap_image() {
        return map_image;
    }

    public void setMap_image(String map_image) {
        this.map_image = map_image;
    }

    public String getDetails_image() {
        return details_image;
    }

    public void setDetails_image(String details_image) {
        this.details_image = details_image;
    }

}
