package thess.tourism.creative.creativetourismthessapp.DbFiles;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table START_POINT.
 */
public class StartPoint {

    private Long id;
    private String NameEn;
    private String NameEl;
    private Double lat;
    private Double longitude;

    public StartPoint() {
    }

    public StartPoint(Long id) {
        this.id = id;
    }

    public StartPoint(Long id, String NameEn, String NameEl, Double lat, Double longitude) {
        this.id = id;
        this.NameEn = NameEn;
        this.NameEl = NameEl;
        this.lat = lat;
        this.longitude = longitude;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getNameEn() {
        return NameEn;
    }

    public void setNameEn(String NameEn) {
        this.NameEn = NameEn;
    }

    public String getNameEl() {
        return NameEl;
    }

    public void setNameEl(String NameEl) {
        this.NameEl = NameEl;
    }

    public Double getLat() {
        return lat;
    }

    public void setLat(Double lat) {
        this.lat = lat;
    }

    public Double getLongitude() {
        return longitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

}
